// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using realty_api_practice.Entities.Data;

#nullable disable

namespace realty_api_practice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260413153225_CreatedLeadsTablesAndDependencies")]
    partial class CreatedLeadsTablesAndDependencies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("realty_api_practice.Entities.Common.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("City", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.Intent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Intents", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetMax")
                        .HasColumnType("int");

                    b.Property<int?>("BudgetMin")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IntentId")
                        .HasColumnType("int");

                    b.Property<int>("LeadSourceId")
                        .HasColumnType("int");

                    b.Property<int>("LeadStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int?>("TimeFrameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IntentId");

                    b.HasIndex("LeadSourceId");

                    b.HasIndex("LeadStatusId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("TimeFrameId");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.LeadAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("UserId");

                    b.HasIndex("LeadId", "UserId");

                    b.ToTable("LeadAssignments", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.LeadSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LeadSources", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.LeadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LeadStatuses", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.LegalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LegalStatus", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.ListingSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ListingSource", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("HOAFees")
                        .HasColumnType("int");

                    b.Property<int>("LegalStatusId")
                        .HasColumnType("int");

                    b.Property<int>("ListingSourceId")
                        .HasColumnType("int");

                    b.Property<int?>("LotSize")
                        .HasColumnType("int");

                    b.Property<int?>("ParkingSpaces")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SquareFeet")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("CityId");

                    b.HasIndex("LegalStatusId");

                    b.HasIndex("ListingSourceId");

                    b.HasIndex("Price");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImage", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PropertyType", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("State", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.TimeFrame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TimeFrames", (string)null);
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.City", b =>
                {
                    b.HasOne("realty_api_practice.Entities.Common.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.Lead", b =>
                {
                    b.HasOne("realty_api_practice.Entities.Common.Intent", "Intents")
                        .WithMany("Leads")
                        .HasForeignKey("IntentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("realty_api_practice.Entities.Common.LeadSource", "LeadSources")
                        .WithMany("Leads")
                        .HasForeignKey("LeadSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("realty_api_practice.Entities.Common.LeadStatus", "LeadStatuses")
                        .WithMany("Leads")
                        .HasForeignKey("LeadStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("realty_api_practice.Entities.Common.Property", "Properties")
                        .WithMany("Leads")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("realty_api_practice.Entities.Common.TimeFrame", "TimeFrames")
                        .WithMany("Leads")
                        .HasForeignKey("TimeFrameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Intents");

                    b.Navigation("LeadSources");

                    b.Navigation("LeadStatuses");

                    b.Navigation("Properties");

                    b.Navigation("TimeFrames");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.LeadAssignment", b =>
                {
                    b.HasOne("realty_api_practice.Entities.Common.Lead", "Lead")
                        .WithMany("LeadAssignments")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("realty_api_practice.Entities.Common.User", "User")
                        .WithMany("LeadAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("User");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.Property", b =>
                {
                    b.HasOne("realty_api_practice.Entities.Common.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("realty_api_practice.Entities.Common.LegalStatus", "LegalStatus")
                        .WithMany("Properties")
                        .HasForeignKey("LegalStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("realty_api_practice.Entities.Common.ListingSource", "ListingSource")
                        .WithMany("Properties")
                        .HasForeignKey("ListingSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("realty_api_practice.Entities.Common.PropertyType", "PropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("LegalStatus");

                    b.Navigation("ListingSource");

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.PropertyImage", b =>
                {
                    b.HasOne("realty_api_practice.Entities.Common.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.Intent", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.Lead", b =>
                {
                    b.Navigation("LeadAssignments");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.LeadSource", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.LeadStatus", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.LegalStatus", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.ListingSource", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.Property", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.PropertyType", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.TimeFrame", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("realty_api_practice.Entities.Common.User", b =>
                {
                    b.Navigation("LeadAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
